export const locationData = ["All", "Hanoi", "Ho Chi Minh", "Da Nang"];
export const keywordData = [
  "Agile",
  "Amazon Web Services (AWS)",
  "Android",
  "Angular",
  "AngularJS",
  "Ansible",
  "ASP.NET",
  "ASP.NET Core",
  "AWS",
  "Back-end Development",
  "Big Data",
  "Blockchain",
  "Bootstrap",
  "Business Analyst",
  "C",
  "C#",
  "C++",
  "Capybara",
  "Chef",
  "Chai",
  "Cloud",
  "Cocos2d",
  "Cucumber",
  "Cypress",
  "Dart",
  "Database",
  "Designer",
  "DevOps",
  "Django",
  "Docker",
  "Eclipse",
  "Elasticsearch",
  "Embedded",
  "English",
  "Ethereum",
  "Express.js",
  "Firebase",
  "Flask",
  "Front-end Development",
  "Full-stack Development",
  "Game",
  "Ginkgo",
  "Git",
  "Golang",
  "GraphQL",
  "Groovy",
  "HTML5",
  "Hybrid",
  "iOS",
  "Internet of Things (IoT)",
  "IntelliJ IDEA",
  "Java",
  "Java Spring",
  "JavaScript",
  "Jasmine",
  "JBehave",
  "Jenkins",
  "Jest",
  "Jinja",
  "JIRA",
  "JMock",
  "JQuery",
  "JSON",
  "JSON Web Encryption (JWE)",
  "JSON Web Key (JWK)",
  "JSON Web Key Set (JWKS)",
  "JSON Web Signature (JWS)",
  "JWT",
  "JUnit",
  "Kanban",
  "Karma",
  "Keras",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "LESS",
  "Linux",
  "Machine Learning",
  "Magento",
  "Material-UI",
  "Microservices",
  "Microsoft Azure",
  "Microsoft SQL Server",
  "Mockito",
  "Mobile App Development",
  "MongoDB",
  "Mocha",
  "MySQL",
  "Natural Language Processing",
  "Network Administration",
  "Network Security",
  "Node.js",
  "NoSQL",
  "NUnit",
  "Objective C",
  "OAuth",
  "OAuth1",
  "OAuth2",
  "OkHttp",
  "OpenID Connect",
  "OpenGL",
  "Oracle",
  "Pandas",
  "Perl",
  "PHP",
  "PostgreSQL",
  "PowerMock",
  "Product Manager",
  "Project Manager",
  "Protractor",
  "PyTest",
  "Python",
  "QA QC",
  "React",
  "React Native",
  "Redis",
  "Redux",
  "Responsive Web Design",
  "RESTful APIs",
  "RSpec",
  "Ruby",
  "Ruby on Rails",
  "RxJava",
  "RxJS",
  "SAP",
  "Sass",
  "Scala",
  "Scikit-learn",
  "Scrum",
  "Semantic UI",
  "Selenium",
  "Server Administration",
  "Sharepoint",
  "SOAP",
  "Software Architect",
  "Software Development Frameworks",
  "Software Development Life Cycle (SDLC)",
  "Software Documentation",
  "Software Integration",
  "Software Maintenance",
  "Software Optimization Techniques",
  "Software Performance Optimization",
  "Software Process Improvement",
  "Software Productivity",
  "Software Project Management",
  "Software Quality Control (QC)",
  "Software Quality Management",
  "Software Requirements Analysis",
  "Software Requirements Management",
  "Software Reverse Engineering",
  "Software Reverse-Compilation",
  "Software Risk Management",
  "Software Robustness Testing",
  "Software Rollback",
  "Software Scalability",
  "Software Scalability Testing",
  "Software Security",
  "Software Security Testing",
  "Software System Analysis",
  "Software System Design",
  "Software Test Automation Frameworks",
  "Software Test Case Management",
  "Software Test Data Management",
  "Software Test Debugging",
  "Software Test Execution",
  "Software Test Performance Monitoring",
  "Software Test Reporting",
  "Software Test Result Analysis",
  "Software Test Scripting",
  "Software Test Validation",
  "Software Test Verification",
  "Software Test Validation and Verification (V&V)",
  "Software Testing",
  "Software Troubleshooting",
  "Software UI-UX Design",
  "Software Usability",
  "Software Usability Testing",
  "Software Versioning",
  "Software Verification",
  "Software Web Scraping",
  "Software WebGL",
  "Software WebRTC",
  "Software WebAssembly",
  "Spring",
  "SQL",
  "Swift",
  "Tailwind CSS",
  "Team Leader",
  "TensorFlow",
  "Test-Driven Development (TDD)",
  "Terraform",
  "TypeScript",
  "UI-UX",
  "Unity",
  "Unittest",
  "User Experience (UX) Design",
  "Version Control (Git)",
  "Virtual Reality",
  "Visual Studio",
  "Vue.js",
  "Web Development",
  "Web Scraping",
  "Web Services (RESTful APIs)",
  "WebGL",
  "Webpack",
  "Wordpress",
  "xUnit",
  "Xamarin",
];

export const schoolData = [
  "Academy of Cryptography Techniques (ACT)",
  "Academy of Journalism and Communication (AJC)",
  "Bach Khoa University (BKU)",
  "Banking Academy (BA)",
  "Can Tho University of Technology (CTUT)",
  "Can Tho University of Medicine – Pharmacy (CTUMP)",
  "Diplomatic Academy of Vietnam (DAV)",
  "Electric Power University (EPU)",
  "Foreign Trade University (FTU)",
  "Foreign Trade University Ho Chi Minh City Campus (FTU2)",
  "FPT University (FPT)",
  "Hanoi Academy of Theater and Cinema (SKDA)",
  "Hanoi Architectural University (HAU)",
  "Hanoi Financial and Banking University (FBU)",
  "Hanoi National University of Education (HNUE)",
  "Hanoi Open University (HOU)",
  "Hanoi University (HANU)",
  "Hanoi University of Business and Technology (HUBT)",
  "Hanoi University of Culture (HUC)",
  "Hanoi University of Industry (HAUI)",
  "Hanoi University of Pharmacy (HUP)",
  "Hanoi University of Public Health (HUPH)",
  "Hanoi University of Transport & Communications (UTC)",
  "Hong Bang International University (HIU)",
  "Ho Chi Minh City Open University (HCMCOU)",
  "Ho Chi Minh City University for Natural Resources and Environment (NRE)",
  "Ho Chi Minh City University of Economics and Finance (UEF)",
  "Ho Chi Minh City University of Technology (HUTECH)",
  "Ho Chi Minh University for Natural Resources and Environment (NRE)",
  "Ho Chi Minh University of Banking (HUB)",
  "Ho Chi Minh University of Transport (HCMUT)",
  "Ho Chi Minh University of Transport & Communications (UTC)",
  "Ho Chi Minh University of Technology (HUTECH)",
  "Hanoi Academy of Theater and Cinema (SKDA)",
  "Hanoi Architectural University (HAU)",
  "Hanoi Financial and Banking University (FBU)",
  "Hanoi National University of Education (HNUE)",
  "Hanoi Open University (HOU)",
  "Hanoi University (HANU)",
  "Hanoi University of Business and Technology (HUBT)",
  "Hanoi University of Culture (HUC)",
  "Hanoi University of Industry (HAUI)",
  "Hanoi University of Pharmacy (HUP)",
  "Hanoi University of Public Health (HUPH)",
  "Hanoi University of Transport & Communications (UTC)",
  "Hong Bang International University (HIU)",
  "Ho Chi Minh City Open University (HCMCOU)",
  "Ho Chi Minh City University for Natural Resources and Environment (NRE)",
  "Ho Chi Minh City University of Economics and Finance (UEF)",
  "Ho Chi Minh City University of Technology (HUTECH)",
  "Ho Chi Minh University for Natural Resources and Environment (NRE)",
  "Ho Chi Minh University of Banking (HUB)",
  "Ho Chi Minh University of Transport (HCMUT)",
  "Ho Chi Minh University of Transport & Communications (UTC)",
  "Ho Chi Minh University of Technology (HUTECH)",
  "Lac Hong University (LHU)",
  "London College of Design & Fashion (LCDF)",
  "Medical University (HMU)",
  "Military Academy of Logistics (MAL)",
  "Military Science Academy (MSA)",
  "National University of Civil Engineering (NUCE)",
  "National Economics University (NEU)",
  "Ngo Quyen University (NQU)",
  "Nguyen Hue University (NHU)",
  "People’s Police University (PPU)",
  "Pham Ngoc Thach University of Medicine (PNT)",
  "Phan Chau Trinh Medical University (PCTMU)",
  "Posts and Telecommunications Institute of Technology (PTIT)",
  "ThaiBinh University of Medicine and Pharmacy (TBUMP)",
  "Thang Long University (TLU)",
  "Ton Duc Thang University (TDTU)",
  "University of Architecture (UAH)",
  "University of Cryptography Techniques (ACT)",
  "University of Economics – Technology for Industries (UNETI)",
  "University of Economics and Law (UEL)",
  "University of Finance and Marketing (UFM)",
  "University of Fire Fighting and Prevention (UFFP)",
  "University of Industrial Fine Art (UIFA)",
  "University of Information Technology (UIT)",
  "University of Languages & International Studies (ULIS)",
  "University of Medicine & Pharmacy (UMP)",
  "University of Science (VNU – US)",
  "Hanoi University of Science & Technology (HUST)",
  "University of Social Science & Humanities (VNU – USSH)",
  "University of Technology (HUTECH)",
  "University of Technology and Education (HCMUTE)",
  "University of Transport (UT)",
  "VietNam Military Medical Academy (VMMA)",
  "VietNam University Of Traditional Medicine (VUTM)",
  "Vietnam Maritime University (VIMARU/VMU)",
  "Vietnam National Academy of Music (VNAM)",
  "Vietnam National University, Ho Chi Minh City (VNU HCMC-MS)",
  "Vietnam National University, Ho Chi Minh City (VNU HCMC-MS)",
  "Water Resources University (WRU)",
];

const Data = { locationData, keywordData };

export default Data;
